zoom: Feature - Additional create meeting parameters.
splunk-soar-connectors/zoom pull request #12
Opened 2024-05-22 18:26 UTC by import-au

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- Added additional parameters to the create meeting action. Additional parameters include:
- Alternative Hosts
- Continous Meeting Chat
- Auto Recording
- Meeting Invitees
- All parameters are documented here: https://developers.zoom.us/docs/meeting-sdk/apis/#operation/meetingCreate

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2024-09-24 08:36 UTC, mmomin-crest approved these changes

2024-09-24 08:40 UTC, gdelavadiya-crest approved these changes

2024-09-25 07:16 UTC, mposluszny-splunk approved these changes

2024-09-25 13:10 UTC, bb-splunk requested changes

2024-09-25 13:10 UTC, bb-splunk commented on zoom_connector.py
> +            data["settings"] = data["settings"] | {"waiting_room": (waiting_room == "True")}
Why use this roundabout logic instead of just inserting the key?

```suggestion
            data["settings"]["waiting_room"] = waiting_room == "True"
```
Same below (where `.update` might be more appropriate

2024-09-25 13:10 UTC, bb-splunk commented on zoom_connector.py
> +                "auto_recording": ("Not Added" if auto_recording == "none" else auto_recording),
Why do other fields have `"None"` capitalized but this one does not?

2024-09-26 11:50 UTC, stutib-crest commented on zoom_connector.py
> +                "auto_recording": ("Not Added" if auto_recording == "none" else auto_recording),
That is because for auto_recording param we have "none" as a value in the value list, and in this case auto_recording will be turned off.

2024-09-26 11:56 UTC, stutib-crest commented on zoom_connector.py
> +            data["settings"] = data["settings"] | {"waiting_room": (waiting_room == "True")}
done

2024-10-01 12:17 UTC, bb-splunk approved these changes

2024-10-01 12:17 UTC, bb-splunk commented on zoom.json
>      "main_module": "zoom_connector.py",
Please bump `min_phantom_version` to fix static tests

2024-10-09 09:39 UTC, stutib-crest commented on zoom.json
>      "main_module": "zoom_connector.py",
done

2024-10-09 17:15 UTC, merged